 export const SideLeftHomeTop = [
  {
    logo: "find.png",
    name: "Find Friends",
  },
  {
    logo: "Group.png",
    name: "Groups",
  },
  {
    logo: "memories.png",
    name: "Memories",
  },
  {
    logo: "saved.png",
    name: "Saved",
  },
  {
    logo: "video.png",
    name: "Video",
  },
  // {
  //   logo: "video.png",
  //   name: "Video",
  // },
  // {
  //   logo: "video.png",
  //   name: "Video",
  // },
];
export const Shurtcuts = [
  {
    photo: "shortcut1.jpg",
    name: "IT job in Cambidia",
  },
  {
    photo: "shortcut2.jpg",
    name: "IT & MEDIA CAMBODIA",
  },
  {
    photo: "shortcut3.png",
    name: "IT job & Technology",
  },
  {
    photo: "shortcut4.jpg",
    name: "IT-Share",
  },
  {
    photo: "shortcut5.jpg",
    name: "Job Cambodia",
  },
];



export const friends = [
  {
    photo: "city-1868530_640.jpg",
    name: "Mario Single",
    comments: ["Cute"],
    Reacts: {
      like: true,
      care: false,
      heart: false,
      wow: false,
      sad: false,
      laugh: false,
      angry: false,
    },
    seenChat: false,
    active: 1,
    status: 1,
    Day: 1,
  },
  {
    photo: "pf1.avif",
    name: "Li Za",
    comments: ["sart"],
    Reacts: {
      like: false,
      care: true,
      heart: false,
      wow: false,
      sad: false,
      laugh: false,
      angry: false,
    },
    seenChat: true,
    active: 1,
    status: 0,
    Day: 1,
  },
  {
    photo: "user3.jpg",
    name: "Ah Lyna",
    comments: ["Love"],
    Reacts: {
      like: false,
      care: false,
      heart: true,
      wow: false,
      sad: false,
      laugh: false,
      angry: false,
    },
    seenChat: true,
    active: 0,
    status: 1,
    Day: 1,
  },
  {
    photo: "user2.jpg",
    name: "Lu Na",
    comments: [],
    Reacts: {
      like: true,
      care: false,
      heart: false,
      wow: false,
      sad: false,
      laugh: false,
      angry: false,
    },
    seenChat: true,
    active: 1,
    status: 1,
    Day: 2,
  },
  {
    photo: "user4.jpg",
    name: "Lorem Ahmary",
    comments: [],
    Reacts: {
      like: true,
      care: false,
      heart: false,
      wow: false,
      sad: false,
      laugh: false,
      angry: false,
    },
    seenChat: true,
    active: 0,
    status: 0,
    Day: 4,
  },
  {
    photo: "user8.avif",
    name: "Jek Rola",
    comments: [],
    Reacts: {
      like: false,
      care: false,
      heart: false,
      wow: false,
      sad: false,
      laugh: false,
      angry: false,
    },
    seenChat: true,
    active: 1,
    status: 1,
    Day: 1,
  },
  {
    photo: "user10.webp",
    name: "John Dia",
    comments: [],
    Reacts: {
      like: false,
      care: false,
      heart: false,
      wow: false,
      sad: false,
      laugh: false,
      angry: false,
    },
    seenChat: true,
    active: 0,
    status: 0,
    Day: 1,
  },
  {
    photo: "user9.avif",
    name: "Ma stek",
    comments: [],
    Reacts: {
      like: false,
      care: false,
      heart: false,
      wow: false,
      sad: false,
      laugh: false,
      angry: true,
    },
    seenChat: false,
    active: 1,
    status: 1,
    Day: 1,
  },
  {
    photo: "user7.avif",
    name: "Hong jerm",
    comments: ["So Beautiful"],
    Reacts: {
      like: false,
      care: false,
      heart: false,
      wow: false,
      sad: false,
      laugh: false,
      angry: false,
    },
    seenChat: false,
    active: 0,
    status: 0,
    Day: 1,
  },
];


export const Users = [
  {
    PfImage: "pf1.avif",
    nameUser: "Li Za",
    description: "Hello my name za, and am single",
    photos: ["pf1.avif"],
    date: "3/14/2024",
    dateHour: "1",
    status: "public",
    reacts: 1000,
    statusReact: "",
    comments: 100,
    shares: 10,
  },
  {
    PfImage: "user4.jpg",
    nameUser: "Ma Rina",
    description: "To day with my boy friend",
    photos: ["man-2425121_640.jpg"],
    date: "3/14/2024",
    dateHour: "1",
    status: "public",
    reacts: 100,
    statusReact: "",
    comments: 100,
    shares: 10,
  },
  {
    PfImage: "city-1868530_640.jpg",
    nameUser: "Mario Single",
    description: "Sad boy",
    photos: [
      "city-1868530_640.jpg",
      "city-1868530_640.jpg",
      "girl-1562025_640.jpg",
    ],
    date: "3/14/2024",
    dateHour: "9",
    status: "public",
    reacts: 200,
    statusReact: "",
    comments: 10,
    shares: 1,
  },
];